//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.4952
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM64DSe.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SM64DSe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] level_ovl_init_EUR {
            get {
                object obj = ResourceManager.GetObject("level_ovl_init_EUR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] level_ovl_init_JAP {
            get {
                object obj = ResourceManager.GetObject("level_ovl_init_JAP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] level_ovl_init_USAv1 {
            get {
                object obj = ResourceManager.GetObject("level_ovl_init_USAv1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] level_ovl_init_USAv2 {
            get {
                object obj = ResourceManager.GetObject("level_ovl_init_USAv2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 0x00 == PLAYER (0xbf)
        ///0x01 == EWB_ICE_A (0xaa)
        ///0x02 == EWB_ICE_B (0xab)
        ///0x03 == EWB_ICE_C (0xac)
        ///0x04 == EWM_ICE_BLOCK (0xad)
        ///0x05 == EMM_LOG (0xae)
        ///0x06 == EMM_YUKA (0xaf)
        ///0x07 == UPDOWN_LIFT (0x1d)
        ///0x08 == HS_UPDOWN_LIFT (0x1e)
        ///0x09 == PATH_LIFT (0x1f)
        ///0x0a == WANWAN (0xdb)
        ///0x0b == CAMERA_TAG (0x14d)
        ///0x0c == SEESAW (0x1c)
        ///0x0d == IRONBALL (0xdc)
        ///0x0e == GORO_ROCK (0xdd)
        ///0x0f == KURIBO (0xc8)
        ///0x10 == KURIBO_S (0xc9)
        ///0x11 == KURIBO_L (0xca)
        ///0x12 == KURIKING (0xc6)
        ///0x13 == BOMBHEI (0xce)
        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string obj_list {
            get {
                return ResourceManager.GetString("obj_list", resourceCulture);
            }
        }
    }
}
