
namespace SM64DSe
{
    public static class Strings
    {
        public static string[] LevelNames = 
        {
            "General purpose test map",
	        "Castle grounds",
	        "Castle - 1st floor",
	        "Castle backyards",
	        "Castle - basement",
	        "Castle - 2nd floor",
	        "Bob-Omb Battlefield",
	        "Whomp's Fortress",
	        "Jolly Roger Bay",
	        "Jolly Roger Bay - ship",
	        "Cool, Cool Mountain",
	        "Cool, Cool Mountain - slider",
	        "Big Boo's Haunt",
	        "Hazy Maze Cave",
	        "Lethal Lava Land",
	        "Lethal Lava Land - volcano",
	        "Shifting Sand Land",
	        "Shifting Sand Land - pyramid",
	        "Dire, Dire Docks",
	        "Snowman's Land",
	        "Snowman's Land - Igloo",
	        "Wet-Dry World",
	        "Tall Tall Mountain",
	        "Tall Tall Mountain - slider",
	        "Tiny-Huge Island - huge",
	        "Tiny-Huge Island - tiny",
	        "Tiny-Huge Island - mountain",
	        "Tick Tock Clock",
	        "Rainbow Ride",
	        "The Princess' Secret Slide",
	        "The Secret Aquarium",
	        "[?] Switch",
	        "The Secret Under the Moat",
	        "Behind the Waterfall",
	        "Over the Rainbows",
	        "Bowser in the Dark World - map",
	        "Bowser in the Dark World - fight",
	        "Bowser in the Fire Sea - map",
	        "Bowser in the Fire Sea - fight",
	        "Bowser in the Sky - map",
	        "Bowser in the Sky - fight",
	        "Tox Box test map",
	        "The Secret of Battle Fort",
	        "Sunshine Isles",
	        "Goomboss Battle - map",
	        "Goomboss Battle - fight",
	        "Big Boo Battle - map",
	        "Big Boo Battle - fight",
	        "Chief Chilly Challenge - map",
	        "Chief Chilly Challenge - fight",
	        "Play Room",
	        "Castle grounds (multiplayer)"
        };

        public static string[] DoorTypes = 
        {
            "Virtual door", 
            "Standard door", 
            "Door with star (0)", 
            "Door with star (1) (WF)",                              
            "Door with star (3) (JRB)", 
            "Door with star (8) (Goomboss)", 
            "Locked door (castle basement)", 
            "Locked door (castle 2nd floor)",                              
            "Standard door", 
            "Bowser door (BitDW)", 
            "Bowser door (BitFS)", 
            "Bowser door (castle 2nd floor)",                 
            "Bowser door (BitS)", 
            "Door with star (1) (playroom)", 
            "Door with star (3) (CCM)", 
            "Old wooden door",                    
            "Rusted metal door", 
            "HMC door", 
            "BBH door", 
            "Character change (Mario)",
            "Character change (Luigi)", 
            "Character change (Wario)", 
            "Locked door (castle entrance)", 
            "Silent room door"
        };
    }
}
